services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybackend
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=klelaravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - application
    command: >
        sh -c "
        until mysqladmin ping -h"mysql" -u root -psecret --silent; do
        echo 'Waiting for MySQL to be ready...';
        sleep 2;
        done;
        echo '✅ MySQL is ready!';
        composer install;
        php artisan migrate;
        php artisan serve --host=0.0.0.0 --port=8000
        "


  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=klelaravel
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - application

networks:
  application:
    driver: bridge

volumes:
  mysql-data:
